controller_frequency: 5.0

TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.8
  min_vel_x: 0.1 

  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_theta:  0.15
  min_vel_theta:  0.05
  min_in_place_vel_theta: 0.05

  acc_lim_x: 1.0
  acc_lim_y: 0.0 
  acc_lim_theta: 1.0

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.0174533

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 4.0
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40
  sim_granularity: 0.045
  angular_sim_granularity: 0.045

  meter_scoring: true
  pdist_scale: 8.0
  gdist_scale: 12.0
  occdist_scale: 0.1
  heading_lookahead: 0.325
  heading_scoring_timestep: 0.8
  heading_scoring: true

# ADD
  dwa: false
