# Planner selection
# base_global_planner: "global_planner/GlobalPlanner"
# base_local_planner: "teb_local_planner/TebLocalPlannerROS"
GlobalPlanner:
  old_navfn_behavior: false
  use_quadratic: true 
  use_dijkstra: true # Use dijkstra's algorithm. Otherwise, A*, default true
  use_grid_path: false
  allow_unknown: false                                
  planner_window_x: 0.0   # default 0.0
  planner_window_y: 0.0   # default 0.0
  default_tolerance: 0.0  # If goal in obstacle, plan to the closest point in radius
  lethal_cost: 253
  neutral_cost: 66 #50
  cost_factor: 0.55 #3.0
  orientation_mode: 0
  visualize_potential: false


