global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 20.0 #3.0
  publish_frequency: 20.0 #3.0
  rolling_window : false
  width: 20.0
  height: 20.0
  resolution: 0.05
  footprint_padding: 0.0
  unknown_cost_value: 254 #add..

  inflation_layer:
    inflation_radius: 1.75 #0.35 #1.75
    cost_scaling_factor: 2.58 #0.3 #2.58
    inflate_unknown: true

  plugins:
    - name: static_map
      type: "costmap_2d::StaticLayer"
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
    - name: virtual_layer
      type: "virtual_costmap_layer::VirtualLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

