local_costmap:
  rolling_window: true
  global_frame: odom #map
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  width: 15
  height: 15
  resolution: 0.05
  transform_tolerance: 0.2
  footprint_padding: 0.0
  unknown_cost_value: 254
  always_send_full_costmap: true

  plugins:
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
    - name: rgbd_obstacle_layer1   
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: rgbd_obstacle_layer2
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: sonar_obstacle_layer_DL
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: sonar_obstacle_layer_DR
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: sonar_obstacle_layer_RL
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: sonar_obstacle_layer_RR
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: virtual_layer2
      type: "virtual_costmap_layer2::VirtualLayer2"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  inflation_layer:
    inflation_radius: 1.75
    cost_scaling_factor: 2.58
    inflate_unknown: true
