local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 5.0

  rolling_window: true
  width: 10.0 #8.0
  height: 10.0 #8.0
  resolution: 0.05
  transform_tolerance: 0.5
  footprint_padding: 0.0

  plugins:
    - name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
    - name: sonar_obstacle_layer_DL
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: sonar_obstacle_layer_DR
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: sonar_obstacle_layer_RL
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: sonar_obstacle_layer_RR
      type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
    - name: virtual_layer
      type: "virtual_costmap_layer::VirtualLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  inflation_layer:
    inflation_radius: 1.75 #0.35
    cost_scaling_factor: 2.58 #3.0
    inflate_unknown: true
