base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:
 odom_topic: odom
 map_frame: map

 # Trajectory
 teb_autosize: true
 dt_ref: 0.3
 dt_hysteresis: 0.03
 min_samples: 3 #5
 max_samples: 50
 global_plan_overwrite_orientation: true
 global_plan_viapoint_sep: 1.0 #0.5
 max_global_plan_lookahead_dist: 5.0
 force_reinit_new_goal_dist: 1.0
 feasibility_check_no_poses: 6 #3
 publish_feedback: false
 shrink_horizon_backup: true
 allow_init_with_backwards_motion: false #true
 exact_arc_length: false
 shrink_horizon_min_duration: 10.0

 # Robot
 max_vel_x: 0.8
 max_vel_y: 0.0
 max_vel_x_backwards: 0.05 #0.15
 max_vel_theta: 0.15
 acc_lim_x: 2.0
 acc_lim_y: 0.0 
 acc_lim_theta: 2.0
 min_turning_radius: 0.0
 wheelbase: 0.0
 cmd_angle_instead_rotvel: false
 footprint_model:
   types: "line"
   line_start: [0.0, 0.0]
   line_end: [-0.188, 0.0]
   #types: "polygon"
   #vertices: [[0.202,0.245], [-0.439,0.245], [-0.439,-0.245], [0.202,-0.245]]
    
 # GoalTolerance
 xy_goal_tolerance: 0.05
 yaw_goal_tolerance: 0.0174533
 free_goal_vel: false

 # Obstacles
 min_obstacle_dist: 0.44
 include_costmap_obstacles: true
 costmap_obstacles_behind_robot_dist: 1.5
 obstacle_poses_affected: 30
 inflation_dist: 0.5
 include_dynamic_obstacles: false
 dynamic_obstacle_inflation_dist: 0.4
 legacy_obstacle_association: false
 obstacle_association_force_inclusion_factor: 1.5
 obstacle_association_cutoff_factor: 5
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: true
 costmap_converter_rate: 5.0

 # Optimization
 no_inner_iterations: 5
 no_outer_iterations: 4
 penalty_epsilon: 0.04
 weight_max_vel_x: 1.0
 weight_max_vel_y: 0.0
 weight_max_vel_theta: 1.0
 weight_acc_lim_x: 0.0
 weight_acc_lim_y: 0.0 
 weight_acc_lim_theta: 0.0
 weight_kinematics_nh: 1000.0
 weight_kinematics_forward_drive: 1000.0
 weight_kinematics_turning_radius: 1.0
 weight_optimaltime: 1.0
 weight_obstacle: 20.0 #50.0
 weight_viapoint: 1.0
 weight_inflation: 0.1
 weight_dynamic_obstacle: 1.0
 weight_dynamic_obstacle_inflation: 1.0

 # Homotopy Class Planner
 enable_homotopy_class_planning: false
 enable_multithreading: true
 simple_exploration: false
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_viapoint_cost_scale: 1.0
 selection_alternative_time_cost: false
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 6
 h_signature_prescaler: 1.0
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: false
 viapoints_all_candidates: true
 switching_blocking_period: 0.0
