#This message is used to send command to tetra
#Conveyor system data read command

int32 num
---
int32 D0_BATTERY_VOLTAGE
int32 D1_SYSTEM_CURRENT
int32 D2_CHARGE_CURRENT
int32 D3_CHARGE_SIGNAL
int32 D4_WHEEL_POWER_STATUS
int32 D5_POWER1_VOLTAGE
int32 D6_POWER2_VOLTAGE
int32 D7_POWER3_VOLTAGE
int32 D8_INPORT_STATUS
int32 D9_OUTPORT_STATUS
int32 D10_POWER_STATUS
int32 D11_SONAR_BUMPER_STATUS
int32 D12_CHARGER_TERMINAL_STATUS

bool command_Result

