#This message is used to send command to tetra
#Get IO Status Check

---
uint8  Input0
uint8  Input1
uint8  Input2
uint8  Input3
uint8  Input4
uint8  Input5
uint8  Input6
uint8  Input7
uint8  Output0
uint8  Output1
uint8  Output2
uint8  Output3
uint8  Output4
uint8  Output5
uint8  Output6
uint8  Output7
bool   command_Result

