#This message is used to send command to tetra
# Set 2D_Pose_Estimate Command

float64 estimate_position_x
float64 estimate_position_y
float64 estimate_position_z
float64 estimate_orientation_x
float64 estimate_orientation_y
float64 estimate_orientation_z
float64 estimate_orientation_w
---
bool command_Result
